version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: seu_banco_de_dados
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    networks:
      - minha-rede  # Adicione esta seção para conectar o serviço à rede

networks:
  minha-rede:
    driver: bridge

